export const categories = [
  { id: 1, name: 'Pizza', emoji: '🍕' },
  { id: 2, name: 'Burger', emoji: '🍔' },
  { id: 3, name: 'Sushi', emoji: '🍣' },
  { id: 4, name: 'Indian', emoji: '🍛' },
  { id: 5, name: 'Chinese', emoji: '🥢' },
  { id: 6, name: 'Dessert', emoji: '🍰' },
];

export const restaurants = [
  {
    id: 1,
    name: 'Mario\'s Pizza Palace',
    cuisine: 'Italian',
    rating: 4.5,
    deliveryTime: '25-30',
    deliveryFee: 2.99,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    promoted: true,
  },
  {
    id: 2,
    name: 'Burger Station',
    cuisine: 'American',
    rating: 4.3,
    deliveryTime: '20-25',
    deliveryFee: 1.99,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    promoted: false,
  },
  {
    id: 3,
    name: 'Sushi Zen',
    cuisine: 'Japanese',
    rating: 4.7,
    deliveryTime: '30-35',
    deliveryFee: 3.99,
    image: 'https://images.pexels.com/photos/1148086/pexels-photo-1148086.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    promoted: false,
  },
  {
    id: 4,
    name: 'Spice Garden',
    cuisine: 'Indian',
    rating: 4.4,
    deliveryTime: '35-40',
    deliveryFee: 2.49,
    image: 'https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
    promoted: true,
  },
];

export const menuItems = [
  {
    id: 1,
    name: 'Margherita Pizza',
    description: 'Fresh mozzarella, tomato sauce, basil leaves',
    price: 18.99,
    image: 'https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Popular',
    popular: true,
  },
  {
    id: 2,
    name: 'Pepperoni Pizza',
    description: 'Classic pepperoni with mozzarella cheese',
    price: 21.99,
    image: 'https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Popular',
    popular: true,
  },
  {
    id: 3,
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce, parmesan, croutons',
    price: 12.99,
    image: 'https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Sides',
    popular: false,
  },
  {
    id: 4,
    name: 'Garlic Bread',
    description: 'Fresh baked bread with garlic butter',
    price: 6.99,
    image: 'https://images.pexels.com/photos/4198018/pexels-photo-4198018.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Sides',
    popular: false,
  },
  {
    id: 5,
    name: 'Coca Cola',
    description: 'Classic Coca Cola 330ml can',
    price: 2.99,
    image: 'https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg?auto=compress&cs=tinysrgb&w=400',
    category: 'Beverages',
    popular: false,
  },
];

export const orders = [
  {
    id: 1,
    restaurantName: 'Mario\'s Pizza Palace',
    items: ['Margherita Pizza x2', 'Caesar Salad x1'],
    total: 52.97,
    status: 'delivered' as const,
    orderTime: '2 hours ago',
    deliveryTime: '45 min',
    address: '123 Main Street, Downtown',
  },
  {
    id: 2,
    restaurantName: 'Burger Station',
    items: ['Classic Burger x1', 'Fries x1', 'Coke x1'],
    total: 28.47,
    status: 'preparing' as const,
    orderTime: '15 min ago',
    deliveryTime: '20-25 min',
    address: '123 Main Street, Downtown',
  },
  {
    id: 3,
    restaurantName: 'Sushi Zen',
    items: ['Salmon Roll x2', 'Miso Soup x1'],
    total: 34.98,
    status: 'on_the_way' as const,
    orderTime: '35 min ago',
    deliveryTime: '5-10 min',
    address: '123 Main Street, Downtown',
  },
];

export const restaurantOrders = [
  {
    id: 1,
    orderNumber: '#1247',
    customer: 'John D.',
    items: ['Margherita Pizza x2', 'Caesar Salad x1'],
    total: 52.97,
    status: 'new' as const,
    time: '2 min ago',
  },
  {
    id: 2,
    orderNumber: '#1246',
    customer: 'Sarah M.',
    items: ['Pepperoni Pizza x1', 'Garlic Bread x1'],
    total: 28.98,
    status: 'preparing' as const,
    time: '15 min ago',
  },
  {
    id: 3,
    orderNumber: '#1245',
    customer: 'Mike L.',
    items: ['Caesar Salad x2', 'Coca Cola x2'],
    total: 31.96,
    status: 'ready' as const,
    time: '25 min ago',
  },
];

export const deliveryOrders = [
  {
    id: 1,
    restaurantName: 'Mario\'s Pizza Palace',
    customerName: 'John D.',
    pickupAddress: '456 Restaurant St',
    deliveryAddress: '123 Main St, Downtown',
    distance: '2.1 miles',
    estimatedTime: '18 min',
    payment: 12.50,
    items: ['Margherita Pizza x2', 'Caesar Salad x1'],
    status: 'available' as const,
  },
  {
    id: 2,
    restaurantName: 'Burger Station',
    customerName: 'Sarah M.',
    pickupAddress: '789 Food Ave',
    deliveryAddress: '456 Oak St, Midtown',
    distance: '1.8 miles',
    estimatedTime: '15 min',
    payment: 9.75,
    items: ['Classic Burger x1', 'Fries x1'],
    status: 'available' as const,
  },
];

export const activeDelivery = {
  id: 3,
  restaurantName: 'Sushi Zen',
  customerName: 'Mike L.',
  customerPhone: '+1 (555) 123-4567',
  pickupAddress: '321 Sushi Blvd',
  deliveryAddress: '789 Pine St, Uptown',
  distance: '3.2 miles',
  estimatedTime: '25 min',
  payment: 15.20,
  status: 'active' as const,
  items: ['Salmon Roll x2', 'Miso Soup x1'],
};